import type { Metadata } from "next";

import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { bubblegum_sans, inter, nova_slim } from "@/fonts";
import idID from "antd/locale/id_ID";
export const metadata: Metadata = {
  title: "Next",
  description: "Generated by create next app",
};

config.autoAddCss = false;
export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <ConfigProvider
      locale={idID}
      theme={{
        token: {},
        components: {
          Input: {
            fontFamily: nova_slim.style.fontFamily,
            fontWeightStrong: nova_slim.style.fontWeight,
          },
          Typography: {
            fontFamily: inter.className,
            fontSize: 15,
          },
          Layout: {},
        },
      }}
    >
      <html lang="en">
        <body className={inter.className} style={{ margin: 0 }}>
          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </html>
    </ConfigProvider>
  );
}
